# Generated by Django 4.1.3 on 2022-11-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_id2',
            field=models.IntegerField(default=-1),
        ),
    ]
