# Generated by Django 4.1.3 on 2022-11-13 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_orders_order_id2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_id2',
        ),
    ]
